services:
  school_backend:
    build: ./server
    container_name: school_backend
    depends_on:
      - boilerplate-db
    env_file:
      - ./server/.env
    ports:
      - "3001:3001"
    networks:
      - boraimpactar2

  school_frontend:
    build: ./client
    container_name: school_frontend
    ports:
      - "8001:8001"
    networks:
      - boraimpactar2

networks:
  boraimpactar2:
    external: true