volumes:
  postgres_data:

services:
  boilerplate-db:
    image: postgres:15
    container_name: school_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: boilerplate
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - boraimpactar2

  school_backend:
    build: ./server
    container_name: school_backend
    depends_on:
      - boilerplate-db
    env_file:
      - ./server/.env
    ports:
      - "3001:3001"
    networks:
      - boraimpactar2

  school_frontend:
    build: ./client
    container_name: school_frontend
    ports:
      - "8001:8001"
    networks:
      - boraimpactar2

networks: 
  boraimpactar2:
    external: true