import { PrismaClient, TeachingStage  } from '@prisma/client';
import { hash } from 'bcryptjs';

const prisma = new PrismaClient();

async function seed() {
  const saltRounds = 6;
  await prisma.schoolManager.deleteMany();
  console.log('Deleted existing school managers.');

  await prisma.schoolManager.createMany({
    data: [
      {
        id: 1,
        fullName: 'ROSANGELA GUSMAO DE SOUZA CORDEIRO',
        phoneNumber: '(81) 91234-5678',
        email: 'rosangela.gusmao@escola.pe.gov.br',
        password: 'senha123',
        schoolName: 'MILTON ALMEIDA DOS SANTOS',
        teachingStages: [TeachingStage.ENSINO_FUNDAMENTAL_I],
        estimatedStudents: 144,
        inepCode: '26419726',
        cep: '51200-000',
        address: 'ITAUBA 2',
        addressNumber: '227',
        addressComplement: 'Bloco A',
        schoolNumber: '424',
        schoolImageUrl: 'https://exemplo.com/imagem-escola-1.jpg',
      },
      {
        id: 2,
        fullName: 'ALEXANDRA LIMA DA PAIXAO STURIALE',
        phoneNumber: '(81) 98765-4321',
        email: 'alexandra.lima@escola.pe.gov.br',
        password: 'senha123',
        schoolName: 'NOSSA SENHORA DA PENHA',
        teachingStages: [TeachingStage.EDUCACAO_INFANTIL],
        estimatedStudents: 225,
        inepCode: '26134049',
        cep: '51020-100',
        address: 'FRANCISCO DE BARROS BARRETO',
        addressNumber: '109',
        addressComplement: 'Sala 2',
        schoolNumber: '150',
        schoolImageUrl: 'https://exemplo.com/imagem-escola-2.jpg',
      },
      {
        id: 3,
        fullName: 'WALESKA BASTOS BARROS',
        phoneNumber: '(81) 99888-1122',
        email: 'waleska.barros@escola.pe.gov.br',
        password: 'senha123',
        schoolName: 'NOVO PINA',
        teachingStages: [
          TeachingStage.ENSINO_FUNDAMENTAL_I,
          TeachingStage.ENSINO_FUNDAMENTAL_II,
        ],
        estimatedStudents: 455,
        inepCode: '26119994',
        cep: '51011-000',
        address: 'EURICO VITRUVIO',
        addressNumber: '236',
        addressComplement: 'Prédio novo',
        schoolNumber: '112',
        schoolImageUrl: 'https://exemplo.com/imagem-escola-3.jpg',
      },
      {
        id: 4,
        fullName: 'ELMA MARIA DOS PRAZERES MOTA CAVALCANTI',
        phoneNumber: '(81) 99111-2233',
        email: 'elma.mota@escola.pe.gov.br',
        password: 'senha123',
        schoolName: 'OSWALDO LIMA FILHO',
        teachingStages: [TeachingStage.ENSINO_FUNDAMENTAL_II],
        estimatedStudents: 624,
        inepCode: '26125510',
        cep: '51011-001',
        address: 'ENGENHEIRO DOMINGOS FERREIRA',
        addressNumber: '1040',
        addressComplement: 'Subsolo',
        schoolNumber: '121',
        schoolImageUrl: 'https://exemplo.com/imagem-escola-4.jpg',
      },
      {
        id: 5,
        fullName: 'EVELINE BEZERRIL CAMPOS FELL',
        phoneNumber: '(81) 99222-3344',
        email: 'eveline.fell@escola.pe.gov.br',
        password: 'senha123',
        schoolName: 'PAIS E FILHOS',
        teachingStages: [TeachingStage.EDUCACAO_INFANTIL],
        estimatedStudents: 351,
        inepCode: '26125528',
        cep: '51200-001',
        address: 'DANCING DAYS',
        addressNumber: '21',
        schoolNumber: '070',
        schoolImageUrl: 'https://exemplo.com/imagem-escola-5.jpg',
      },
      {
        id: 6,
        fullName: 'ROSINALVA MONTEIRO DA SILVA',
        phoneNumber: '(81) 99333-4455',
        email: 'rosinalva.silva@escola.pe.gov.br',
        password: 'senha123',
        schoolName: 'PASTOR JOSE MUNGUBA SOBRINHO',
        teachingStages: [TeachingStage.ENSINO_FUNDAMENTAL_I],
        estimatedStudents: 295,
        inepCode: '26157888',
        cep: '51190-000',
        address: 'SILVA JARDIM',
        addressNumber: '145',
        schoolNumber: '348',
        schoolImageUrl: 'https://exemplo.com/imagem-escola-6.jpg',
      },
      {
        id: 7,
        fullName: 'OZANIRA MARIA PEREIRA GOMES DA SILVA',
        phoneNumber: '(81) 99444-5566',
        email: 'ozanira.silva@escola.pe.gov.br',
        password: 'senha123',
        schoolName: 'PAZ E AMOR',
        teachingStages: [TeachingStage.EDUCACAO_INFANTIL],
        estimatedStudents: 134,
        inepCode: '26187957',
        cep: '51210-000',
        address: 'JORNALISTA EDSOU REGIS',
        addressNumber: '216',
        schoolNumber: '491',
        schoolImageUrl: 'https://exemplo.com/imagem-escola-7.jpg',
      },
      {
        id: 8,
        fullName: 'FLORISMAM LIMA DE OLIVEIRA',
        phoneNumber: '(81) 99555-6677',
        email: 'florismam.lima@escola.pe.gov.br',
        password: 'senha123',
        schoolName: 'PINTOR LULA CARDOSO AYRES',
        teachingStages: [TeachingStage.ENSINO_FUNDAMENTAL_II],
        estimatedStudents: 299,
        inepCode: '26132249',
        cep: '51191-000',
        address: 'DR ALVARO FERRAZ',
        addressNumber: '594',
        schoolNumber: '106',
        schoolImageUrl: 'https://exemplo.com/imagem-escola-8.jpg',
      },
      {
        id: 9,
        fullName: 'CINTHIA FERREIRA DA SILVA',
        phoneNumber: '(81) 99666-7788',
        email: 'cinthia.ferreira@escola.pe.gov.br',
        password: 'senha123',
        schoolName: 'POETA JOAO CABRAL DE MELO NETO',
        teachingStages: [TeachingStage.ENSINO_FUNDAMENTAL_I],
        estimatedStudents: 305,
        inepCode: '26168138',
        cep: '51012-000',
        address: 'ENCANTA MOCA',
        addressNumber: '377',
        schoolNumber: '928',
        schoolImageUrl: 'https://exemplo.com/imagem-escola-9.jpg',
      },
      {
        id: 10,
        fullName: 'MARIA ANDREZA CABRAL DA SILVA',
        phoneNumber: '(81) 99777-8899',
        email: 'andreza.cabral@escola.pe.gov.br',
        password: 'senha123',
        schoolName: 'POETA PAULO BANDEIRA DA CRUZ',
        teachingStages: [
          TeachingStage.EDUCACAO_INFANTIL,
          TeachingStage.ENSINO_FUNDAMENTAL_I,
          TeachingStage.ENSINO_FUNDAMENTAL_II,
        ],
        estimatedStudents: 485,
        inepCode: '26125544',
        cep: '51500-000',
        address: 'DAS PANELAS',
        addressNumber: '28',
        schoolNumber: '164',
        schoolImageUrl: 'https://exemplo.com/imagem-escola-10.jpg',
      },
    ],
  });
  console.log('School Managers created successfully');
}

seed().then(() => {
  console.log('Database successfully seeded');
  prisma.$disconnect();
});
